config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yprov:
      branch: main
      repo: https://github.com/HPCI-Lab/yprov
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yprov git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-puce-uguisu.sh
        container: qc.acc_scaly-magnolia-mole
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yprov find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-eggplant-dingo.sh
        container: qc.doc_dorky-wheat-sparrow
      github.com/HPCI-Lab/yprov git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-vermilion-russel.sh
        container: qc.doc_surly-pumpkin-uakari
      github.com/HPCI-Lab/yprov markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-flax-mandrill.sh
        container: qc.doc_skimpy-white-birman
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yprov licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-thistle-cougar.sh
        container: qc.lic_lovely-emerald-slug
  QC.Met:
    repos:
      github.com/HPCI-Lab/yprov cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cinnabar-ostrich.sh
        container: qc.met_nerdy-grey-urchin
      github.com/HPCI-Lab/yprov validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-asparagus-grasshopper.sh
        container: qc.met_snoopy-pear-markhor
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yprov bandit:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-jade-burmese.sh
        container: qc.sec_seedy-scarlet-stingray
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yprov flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-burgundy-mayfly.sh
        container: qc.sty_cozy-corn-serval
      github.com/HPCI-Lab/yprov hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-beige-sparrow.sh
        container: qc.sty_flimsy-alizarin-ray
      github.com/HPCI-Lab/yprov jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-violet-serval.sh
        container: qc.sty_breezy-brass-hyena
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yprov pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cerulean-sparrow.sh
        container: qc.uni_freaky-blue-crocodile
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yprov get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-cornflower-macaque.sh
        container: qc.ver_lovely-asparagus-stoat
timeout: 5400
