config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-bronze-ragdoll.sh
        container: qc.acc_hasty-brown-tarsier
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-khaki-frog.sh
        container: qc.doc_baggy-coral-moth
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-brown-pig.sh
        container: qc.doc_tacky-sangria-discus
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-tangerine-gharial.sh
        container: qc.doc_tasty-orchid-squid
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-wheat-bat.sh
        container: qc.lic_nerdy-cinnabar-moth
  QC.Met:
    repos:
      github.com/HPCI-Lab/yProv cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-cream-weasel.sh
        container: qc.met_whiny-charcoal-javanese
      github.com/HPCI-Lab/yProv validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-emerald-slug.sh
        container: qc.met_freaky-platinum-ostrich
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-copper-kakapo.sh
        container: qc.sec_flaky-viridian-olm
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-corn-chimpanzee.sh
        container: qc.sty_surly-eggplant-kingfisher
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-amethyst-zorse.sh
        container: qc.sty_nerdy-periwinkle-boar
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-goldenrod-insect.sh
        container: qc.sty_skinny-myrtle-javanese
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-auburn-chipmunk.sh
        container: qc.uni_sleazy-platinum-uakari
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-yellow-armadillo.sh
        container: qc.ver_sleazy-thistle-rabbit
timeout: 5400
