config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: NSQA
      repo: https://github.com/HPCI-Lab/yProv
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-apricot-catfish.sh
        container: qc.acc_hasty-sangria-vole
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-lemon-tortoise.sh
        container: qc.doc_lanky-azure-dog
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-ruby-barb.sh
        container: qc.doc_messy-auburn-bordeaux
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-peach-hyena.sh
        container: qc.doc_gummy-cardinal-mist
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-wheat-uakari.sh
        container: qc.lic_stuffy-chestnut-budgerigar
  QC.Met:
    repos:
      github.com/HPCI-Lab/yProv cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-ultramarine-badger.sh
        container: qc.met_lumpy-beige-raccoon
      github.com/HPCI-Lab/yProv validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.surly-pumpkin-loon.sh
        container: qc.met_gimpy-peach-kudu
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cardinal-zebra.sh
        container: qc.sec_wiggy-mauve-cow
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-wheat-cow.sh
        container: qc.sty_goopy-periwinkle-akita
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-vermilion-bloodhound.sh
        container: qc.sty_shaggy-auburn-monster
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-indigo-kingfisher.sh
        container: qc.sty_wimpy-charcoal-axolotl
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.messy-orchid-starfish.sh
        container: qc.uni_homely-tomato-newt
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-rust-cattle.sh
        container: qc.ver_surly-apricot-drever
timeout: 5400
