config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: sqa
      repo: https://github.com/HPCI-Lab/yProv
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-wheat-nightingale.sh
        container: qc.acc_goopy-apricot-angora
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-platinum-tiger.sh
        container: qc.doc_pasty-bronze-fousek
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-carmine-squirrel.sh
        container: qc.doc_wimpy-aqua-sponge
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-ochre-akita.sh
        container: qc.doc_slaphappy-periwinkle-lion
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-tan-rhinoceros.sh
        container: qc.lic_scummy-sepia-moose
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-aqua-bongo.sh
        container: qc.sec_wimpy-mauve-lizard
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-denim-elephant.sh
        container: qc.sty_zippy-amethyst-crane
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-peach-monster.sh
        container: qc.sty_blurry-tomato-reindeer
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-violet-caiman.sh
        container: qc.sty_goopy-dandelion-newt
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-auburn-woodlouse.sh
        container: qc.uni_pretty-amethyst-flounder
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-azure-newfoundland.sh
        container: qc.ver_surly-beige-monkey
timeout: 5400
