config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: sqa
      repo: https://github.com/HPCI-Lab/yProv
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-beige-sloth.sh
        container: qc.acc_pokey-khaki-dane
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-violet-cuttlefish.sh
        container: qc.doc_blurry-rust-badger
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-mustard-macaw.sh
        container: qc.doc_chewy-magnolia-whippet
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-ecru-ray.sh
        container: qc.doc_beady-khaki-spider
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-jade-horse.sh
        container: qc.lic_crappy-yellow-serval
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-viridian-giraffe.sh
        container: qc.sec_chummy-magnolia-retriever
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-eggplant-vole.sh
        container: qc.sty_geeky-silver-axolotl
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-taupe-indri.sh
        container: qc.sty_jumpy-magenta-yak
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-bistre-foxhound.sh
        container: qc.sty_goopy-flax-barracuda
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-aqua-lemur.sh
        container: qc.uni_woozy-harlequin-affenpinscher
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-tan-bullfrog.sh
        container: qc.ver_thirsty-thistle-lynx
timeout: 5400
